### ISSUE TITLE
error requiring secure_random

### ISSUE THREAD

**Issue by lebogan** [faustinoaq/ruby2crystal#1]
I ran into this error somewhere else, but I can't remember what I did to fix it. It looks like an error in amber?
```
Error target ruby2crystal failed to compile:
Error in src/ruby2crystal.cr:1: while requiring "../config/*"

require "../config/*"


in config/application.cr:1: while requiring "amber"

require "amber"

in lib/amber/src/amber.cr:5: while requiring "secure_random": can't find file 'secure_random'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

require "secure_random"
```
Thank you for considering this issue. I'm coming from a Ruby world and this looks like a good tool to help me get a grip on Crystal.

**Comment by faustinoaq** [comment]
Hi @lebogan this project is oudated (non compatible with most recent crystal/amber versions)

I'll update this once I get time :+1:

**Comment by faustinoaq** [comment]
Updated :+1:
